#
# Module manifest for module 'PrimeTime'
#
# Generated by: James Brundage
#
# Generated on: 1/27/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PrimeTime.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '96c04e23-5394-46f5-9153-29f5fcea859f'

# Author of this module
Author = 'James Brundage'

# Company or vendor of this module
CompanyName = 'Start-Automating'

# Copyright statement for this module
Copyright = '2026 Start-Automating'

# Description of the functionality provided by this module
Description = 'The Power of Primes'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @('PrimeTime.types.ps1xml')

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-PrimeTime', 'Get-Prime'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'PrimeTime', 'Prime'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/PoshWeb/PrimeTime/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/PoshWeb/PrimeTime'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()
        PSIntro = @'
### About PrimeTime

PrimeTime is a simple animation framework

PrimeTime uses The Power of Primes

PrimeTime defines prime intervals for animation

Primes rarely overlap

This helps animation feel alive

### PrimeTime Pages

We can use PrimeTime in any webpage

Just link to the stylesheet

```html
<link rel='stylesheet' href='https://PrimeTime.PoshWeb.org/PrimeTime.css' />
```

### PrimeTime Demos

The PrimeTime logo animates eight primes:

```PowerShell
7 * 11 * 13 * 17 * 19 * 23 * 29 * 31
```

The logo will repeat every `6685349671` seconds, or _almost 212 years_.

The [PrimeTime page](https://primetime.poshweb.org/) background uses 56 primes.

This background will repeat every `8.84753141993573E+116` seconds.

That's exponential notation.

This is a mind-boggling large number (so large it overflows the .NET `[TimeSpan]`).

Turn that interval into years and it's _still_ mind-boggling.

**The Background Will Repeat every 100 Billion Years**
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

